on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
permissions:
  packages: write
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install AWS PowerShell module locally
        id: installawspwsh
        shell: pwsh
        run: |
          ./install-aws-powershell.ps1
          
      - name: Get AWS PowerShell Module Version
        shell: pwsh
        run: |
          Write-Host -Object 'Module version is: ${{ steps.installawspwsh.outputs.MODULE_VERSION }}'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.installawspwsh.outputs.MODULE_VERSION }}

      - name: Build Docker image
        id: dockerbuild
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
