on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
permissions:
  packages: write
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.4.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        id: dockerbuild
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Grab module version
        shell: pwsh
        run: |
          Write-Host -Object 'Getting module version'
          Write-Host -Object '${{ steps.dockerbuild.outputs.MODULE_VERSION }}'
          Write-Host -Object '${{ env.MODULE_VERSION }}'
        
      - name: Build Docker image
        id: dockerpush
        uses: docker/build-push-action@v2.6.1
        with:
          build: false
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
